export type AssessmentItem = { code: string; text: string };
export type AssessmentModule = {
  code: "MENGENAL_DIRI" | "MEMAHAMI_DIRI" | "MENENTUKAN_ARAH";
  title: string;
  subtitle: string;
  question: string;
  restricted?: boolean;
  items: AssessmentItem[];
};

const q = (code: string, text: string): AssessmentItem => ({ code, text });

export const ASSESSMENT_MODULES: AssessmentModule[] = [
  {
    code: "MENGENAL_DIRI",
    title: "Mengenal Diri",
    subtitle: "Profil Karakter, Temperamen & Gaya Interaksi",
    question: "Saya ini orang seperti apa?",
    items: [
      q("SG1", "Saya mudah memulai percakapan dengan orang yang baru saya kenal."),
      q("SG2", "Saya sering membuat suasana kelompok menjadi lebih hidup."),
      q("SG3", "Saya cukup terbuka mengekspresikan antusiasme."),
      q("SG4", "Saya menikmati kegiatan yang melibatkan banyak interaksi dengan orang lain."),
      q("KL1", "Ketika kelompok belum memiliki arah, saya cenderung mengambil inisiatif."),
      q("KL2", "Saya cukup nyaman mengambil keputusan ketika situasi membutuhkan tindakan."),
      q("KL3", "Saya senang bekerja dengan target dan hasil yang jelas."),
      q("KL4", "Ketika muncul masalah, pikiran saya cepat tertuju pada apa yang dapat dilakukan."),
      q("ML1", "Saya biasanya memikirkan berbagai kemungkinan sebelum mengambil keputusan."),
      q("ML2", "Saya cukup memperhatikan detail dalam pekerjaan."),
      q("ML3", "Saya lebih nyaman ketika kegiatan memiliki rencana yang jelas."),
      q("ML4", "Saya sering memeriksa kembali hasil pekerjaan sebelum dianggap selesai."),
      q("PL1", "Saya cenderung tetap tenang ketika terjadi ketegangan dalam kelompok."),
      q("PL2", "Saya lebih suka mencari jalan tengah ketika terjadi perbedaan pendapat."),
      q("PL3", "Saya cukup sabar mendengarkan orang lain menjelaskan masalahnya."),
      q("PL4", "Saya nyaman bekerja dengan ritme yang stabil dan tidak terburu-buru."),
      q("IN1", "Saya berusaha menepati janji atau komitmen meskipun tidak ada yang mengingatkan."),
      q("IN2", "Saya bersedia mengakui kesalahan dan menjaga kepercayaan ketika diberi amanah."),
      q("SA1", "Saya dapat mengenali kekuatan sekaligus kekurangan diri saya."),
      q("SA2", "Saya terbuka menerima masukan dan mengevaluasi diri setelah melakukan kesalahan."),
      q("SP1", "Nilai agama yang saya yakini menjadi pertimbangan dalam keputusan penting."),
      q("SP2", "Saya berusaha menerapkan pelajaran dari kajian atau pembinaan dalam kehidupan sehari-hari."),
      q("TJ1", "Saya berusaha menyelesaikan tanggung jawab yang sudah saya terima."),
      q("TJ2", "Saya menjaga kualitas pekerjaan meskipun tidak selalu diawasi."),
      q("RE1", "Saya tetap mencoba ketika menghadapi tugas atau keadaan yang sulit."),
      q("RE2", "Ketika cara pertama tidak berhasil, saya mencari pendekatan lain."),
      q("IS1", "Saya bersedia mengambil tanggung jawab baru untuk berkembang."),
      q("IS2", "Saya dapat mengubah gagasan menjadi langkah atau tindakan nyata."),
      q("KO1", "Saya dapat bekerja dengan orang yang memiliki pandangan berbeda."),
      q("KO2", "Saya memberi ruang kepada orang lain untuk menyampaikan pendapat."),
      q("LE1", "Ketika dibutuhkan, saya bersedia membantu kelompok menentukan arah."),
      q("LE2", "Saya senang membantu orang lain berkembang, bukan hanya menyelesaikan bagian saya sendiri."),
      q("KS1", "Saya tertarik menggunakan kemampuan saya untuk memberikan manfaat kepada orang lain."),
      q("KS2", "Saya ingin pengetahuan dan pengalaman saya kelak memberi manfaat bagi masyarakat atau daerah."),
    ],
  },
  {
    code: "MEMAHAMI_DIRI",
    title: "Memahami Diri",
    subtitle: "Emosi, Ketangguhan & Kebutuhan Pendampingan",
    question: "Apa yang sedang terjadi dalam diri saya?",
    restricted: true,
    items: [
      q("EA1", "Saya cukup mampu mengenali apa yang sedang saya rasakan."),
      q("EA2", "Saya biasanya mengetahui hal apa yang membuat suasana hati saya berubah."),
      q("EA3", "Saya menyadari ketika emosi mulai memengaruhi keputusan saya."),
      q("ER1", "Ketika marah atau kecewa, saya mampu memberi waktu kepada diri sendiri sebelum bertindak."),
      q("ER2", "Saya mempunyai cara yang cukup sehat untuk menenangkan diri ketika tertekan."),
      q("ER3", "Saya dapat kembali fokus setelah mengalami situasi emosional."),
      q("RR1", "Saya dapat menerima bahwa tidak semua hal berjalan sesuai rencana."),
      q("RR2", "Setelah mengalami kegagalan, saya biasanya dapat kembali bergerak."),
      q("RR3", "Ketika satu cara tidak berhasil, saya masih mampu mencari pilihan lain."),
      q("OP1", "Saya sering menyimpan masalah sendiri terlalu lama."),
      q("OP2", "Saya terkadang merasa harus terlihat baik-baik saja di depan orang lain."),
      q("OP3", "Saya sulit menceritakan masalah pribadi kepada orang lain."),
      q("AC1", "Saya terkadang terlalu keras menyalahkan diri sendiri ketika melakukan kesalahan."),
      q("AC2", "Saya sering memikirkan kekurangan diri lebih lama daripada keberhasilan yang saya capai."),
      q("SU1", "Saya memiliki setidaknya satu orang yang benar-benar dapat saya percaya untuk bercerita."),
      q("SU2", "Saya merasa memiliki orang yang dapat membantu ketika sedang mengalami masa sulit."),
      q("HS1", "Saya cukup nyaman meminta bantuan ketika memang membutuhkannya."),
      q("HS2", "Saya merasa lingkungan ETOS dapat menjadi salah satu tempat untuk mencari dukungan."),
      q("XF1", "Ada persoalan keluarga yang belakangan ini cukup memengaruhi pikiran saya."),
      q("XR1", "Ada persoalan pertemanan atau hubungan dengan orang lain yang sedang mengganggu saya."),
      q("XA1", "Tekanan akademik belakangan ini terasa cukup berat bagi saya."),
      q("XM1", "Saya sedang cukup bingung mengenai diri atau masa depan saya."),
      q("CK1", "Saya merasa ada sesuatu yang ingin saya bicarakan secara pribadi dengan fasilitator."),
      q("CK2", "Saya merasa akan terbantu jika mendapat pendampingan lebih dekat dalam beberapa waktu ke depan."),
    ],
  },
  {
    code: "MENENTUKAN_ARAH",
    title: "Menentukan Arah",
    subtitle: "Minat, Cita-Cita, Karier & Kontribusi",
    question: "Saya ingin menjadi siapa dan menuju ke mana?",
    items: [
      q("FC1", "Saya sudah memiliki gambaran mengenai profesi yang ingin saya jalani."),
      q("FC2", "Saya mengetahui kemampuan apa yang perlu saya bangun untuk mendekati cita-cita saya."),
      q("FC3", "Saya memiliki target tertentu yang ingin saya capai selama masa kuliah."),
      q("FE1", "Saya mempunyai beberapa pilihan karier yang sedang saya pertimbangkan."),
      q("FE2", "Saya masih ingin mencoba banyak pengalaman sebelum menentukan pilihan karier."),
      q("FE3", "Saya ingin masa kuliah menjadi waktu untuk menemukan arah hidup dengan lebih jelas."),
      q("R1", "Saya menikmati kegiatan yang menggunakan alat, teknologi, atau keterampilan praktis."),
      q("R2", "Saya tertarik membuat, merakit, memperbaiki, atau mengoperasikan sesuatu."),
      q("I1", "Saya menikmati mencari tahu penyebab suatu masalah."),
      q("I2", "Saya tertarik melakukan penelitian, analisis, atau mempelajari sesuatu secara mendalam."),
      q("A1", "Saya menikmati menciptakan ide, desain, tulisan, konten, atau karya."),
      q("A2", "Saya menyukai aktivitas yang memberi ruang besar untuk kreativitas dan ekspresi."),
      q("S1", "Saya menikmati membantu orang memahami sesuatu."),
      q("S2", "Saya senang ketika dapat mendampingi atau memberi manfaat langsung kepada orang lain."),
      q("E1", "Saya menikmati mengajak orang lain bergerak mencapai suatu tujuan."),
      q("E2", "Saya tertarik membangun usaha, organisasi, program, atau sesuatu yang dapat berkembang."),
      q("C1", "Saya menikmati mengatur data, sistem, jadwal, atau pekerjaan agar lebih rapi."),
      q("C2", "Saya nyaman mengerjakan sesuatu yang membutuhkan ketelitian dan keteraturan."),
      q("AL1", "Saya tertarik memimpin organisasi, tim, atau project."),
      q("AE1", "Saya tertarik membangun usaha sendiri atau menjadi entrepreneur."),
      q("AS1", "Saya tertarik menghasilkan dampak sosial melalui pekerjaan atau kegiatan saya."),
      q("AG1", "Saya ingin memiliki pengalaman belajar atau bekerja di luar daerah atau lingkungan internasional."),
      q("CP1", "Saya tertarik bekerja di perusahaan atau lingkungan profesional."),
      q("CE1", "Saya tertarik menjadikan entrepreneurship sebagai salah satu jalur masa depan."),
      q("CA1", "Saya tertarik menjadi akademisi, peneliti, atau melanjutkan pendidikan tinggi."),
      q("CG1", "Saya tertarik bekerja di pemerintahan atau pelayanan publik."),
      q("CS1", "Saya tertarik bekerja dalam NGO, organisasi sosial, atau community development."),
      q("CD1", "Saya tertarik menjadi pendidik atau terlibat dalam pengembangan manusia."),
      q("VN1", "Saya ingin pekerjaan saya memberikan manfaat nyata bagi orang lain."),
      q("VF1", "Saya ingin memiliki kemandirian finansial."),
      q("VS1", "Saya ingin kehidupan profesional saya tetap selaras dengan nilai agama."),
      q("VL1", "Saya ingin terus memperoleh pengalaman dan pengetahuan baru sepanjang hidup."),
      q("KD1", "Ada persoalan di masyarakat atau daerah asal yang suatu saat ingin saya bantu selesaikan."),
      q("KD2", "Saya ingin menggunakan bidang ilmu saya untuk memberikan manfaat kepada masyarakat."),
    ],
  },
];

export const TOTAL_QUESTIONS = ASSESSMENT_MODULES.reduce((total, module) => total + module.items.length, 0);
