-- Seed the 3 ETOS modules and all 92 existing questions.

insert into public.assessment_modules (code,title,subtitle,reflection_question,sort_order,is_restricted) values
('MENGENAL_DIRI','Mengenal Diri','Profil Karakter, Temperamen & Gaya Interaksi','Saya ini orang seperti apa?',1,false),
('MEMAHAMI_DIRI','Memahami Diri','Emosi, Ketangguhan & Kebutuhan Pendampingan','Apa yang sedang terjadi dalam diri saya?',2,true),
('MENENTUKAN_ARAH','Menentukan Arah','Minat, Cita-Cita, Karier & Kontribusi','Saya ingin menjadi siapa dan menuju ke mana?',3,false)
on conflict (code) do update set title=excluded.title, subtitle=excluded.subtitle, reflection_question=excluded.reflection_question, sort_order=excluded.sort_order, is_restricted=excluded.is_restricted;

with src(module_code,code,statement,dimension,sensitivity,sort_order) as (values
('MENGENAL_DIRI','SG1','Saya mudah memulai percakapan dengan orang yang baru saya kenal.','SG','standard',1),
('MENGENAL_DIRI','SG2','Saya sering membuat suasana kelompok menjadi lebih hidup.','SG','standard',2),
('MENGENAL_DIRI','SG3','Saya cukup terbuka mengekspresikan antusiasme.','SG','standard',3),
('MENGENAL_DIRI','SG4','Saya menikmati kegiatan yang melibatkan banyak interaksi dengan orang lain.','SG','standard',4),
('MENGENAL_DIRI','KL1','Ketika kelompok belum memiliki arah, saya cenderung mengambil inisiatif.','KL','standard',5),
('MENGENAL_DIRI','KL2','Saya cukup nyaman mengambil keputusan ketika situasi membutuhkan tindakan.','KL','standard',6),
('MENGENAL_DIRI','KL3','Saya senang bekerja dengan target dan hasil yang jelas.','KL','standard',7),
('MENGENAL_DIRI','KL4','Ketika muncul masalah, pikiran saya cepat tertuju pada apa yang dapat dilakukan.','KL','standard',8),
('MENGENAL_DIRI','ML1','Saya biasanya memikirkan berbagai kemungkinan sebelum mengambil keputusan.','ML','standard',9),
('MENGENAL_DIRI','ML2','Saya cukup memperhatikan detail dalam pekerjaan.','ML','standard',10),
('MENGENAL_DIRI','ML3','Saya lebih nyaman ketika kegiatan memiliki rencana yang jelas.','ML','standard',11),
('MENGENAL_DIRI','ML4','Saya sering memeriksa kembali hasil pekerjaan sebelum dianggap selesai.','ML','standard',12),
('MENGENAL_DIRI','PL1','Saya cenderung tetap tenang ketika terjadi ketegangan dalam kelompok.','PL','standard',13),
('MENGENAL_DIRI','PL2','Saya lebih suka mencari jalan tengah ketika terjadi perbedaan pendapat.','PL','standard',14),
('MENGENAL_DIRI','PL3','Saya cukup sabar mendengarkan orang lain menjelaskan masalahnya.','PL','standard',15),
('MENGENAL_DIRI','PL4','Saya nyaman bekerja dengan ritme yang stabil dan tidak terburu-buru.','PL','standard',16),
('MENGENAL_DIRI','IN1','Saya berusaha menepati janji atau komitmen meskipun tidak ada yang mengingatkan.','IN','standard',17),
('MENGENAL_DIRI','IN2','Saya bersedia mengakui kesalahan dan menjaga kepercayaan ketika diberi amanah.','IN','standard',18),
('MENGENAL_DIRI','SA1','Saya dapat mengenali kekuatan sekaligus kekurangan diri saya.','SA','standard',19),
('MENGENAL_DIRI','SA2','Saya terbuka menerima masukan dan mengevaluasi diri setelah melakukan kesalahan.','SA','standard',20),
('MENGENAL_DIRI','SP1','Nilai agama yang saya yakini menjadi pertimbangan dalam keputusan penting.','SP','standard',21),
('MENGENAL_DIRI','SP2','Saya berusaha menerapkan pelajaran dari kajian atau pembinaan dalam kehidupan sehari-hari.','SP','standard',22),
('MENGENAL_DIRI','TJ1','Saya berusaha menyelesaikan tanggung jawab yang sudah saya terima.','TJ','standard',23),
('MENGENAL_DIRI','TJ2','Saya menjaga kualitas pekerjaan meskipun tidak selalu diawasi.','TJ','standard',24),
('MENGENAL_DIRI','RE1','Saya tetap mencoba ketika menghadapi tugas atau keadaan yang sulit.','RE','standard',25),
('MENGENAL_DIRI','RE2','Ketika cara pertama tidak berhasil, saya mencari pendekatan lain.','RE','standard',26),
('MENGENAL_DIRI','IS1','Saya bersedia mengambil tanggung jawab baru untuk berkembang.','IS','standard',27),
('MENGENAL_DIRI','IS2','Saya dapat mengubah gagasan menjadi langkah atau tindakan nyata.','IS','standard',28),
('MENGENAL_DIRI','KO1','Saya dapat bekerja dengan orang yang memiliki pandangan berbeda.','KO','standard',29),
('MENGENAL_DIRI','KO2','Saya memberi ruang kepada orang lain untuk menyampaikan pendapat.','KO','standard',30),
('MENGENAL_DIRI','LE1','Ketika dibutuhkan, saya bersedia membantu kelompok menentukan arah.','LE','standard',31),
('MENGENAL_DIRI','LE2','Saya senang membantu orang lain berkembang, bukan hanya menyelesaikan bagian saya sendiri.','LE','standard',32),
('MENGENAL_DIRI','KS1','Saya tertarik menggunakan kemampuan saya untuk memberikan manfaat kepada orang lain.','KS','standard',33),
('MENGENAL_DIRI','KS2','Saya ingin pengetahuan dan pengalaman saya kelak memberi manfaat bagi masyarakat atau daerah.','KS','standard',34),
('MEMAHAMI_DIRI','EA1','Saya cukup mampu mengenali apa yang sedang saya rasakan.','EA','private',1),
('MEMAHAMI_DIRI','EA2','Saya biasanya mengetahui hal apa yang membuat suasana hati saya berubah.','EA','private',2),
('MEMAHAMI_DIRI','EA3','Saya menyadari ketika emosi mulai memengaruhi keputusan saya.','EA','private',3),
('MEMAHAMI_DIRI','ER1','Ketika marah atau kecewa, saya mampu memberi waktu kepada diri sendiri sebelum bertindak.','ER','private',4),
('MEMAHAMI_DIRI','ER2','Saya mempunyai cara yang cukup sehat untuk menenangkan diri ketika tertekan.','ER','private',5),
('MEMAHAMI_DIRI','ER3','Saya dapat kembali fokus setelah mengalami situasi emosional.','ER','private',6),
('MEMAHAMI_DIRI','RR1','Saya dapat menerima bahwa tidak semua hal berjalan sesuai rencana.','RR','private',7),
('MEMAHAMI_DIRI','RR2','Setelah mengalami kegagalan, saya biasanya dapat kembali bergerak.','RR','private',8),
('MEMAHAMI_DIRI','RR3','Ketika satu cara tidak berhasil, saya masih mampu mencari pilihan lain.','RR','private',9),
('MEMAHAMI_DIRI','OP1','Saya sering menyimpan masalah sendiri terlalu lama.','OP','signal',10),
('MEMAHAMI_DIRI','OP2','Saya terkadang merasa harus terlihat baik-baik saja di depan orang lain.','OP','signal',11),
('MEMAHAMI_DIRI','OP3','Saya sulit menceritakan masalah pribadi kepada orang lain.','OP','signal',12),
('MEMAHAMI_DIRI','AC1','Saya terkadang terlalu keras menyalahkan diri sendiri ketika melakukan kesalahan.','AC','signal',13),
('MEMAHAMI_DIRI','AC2','Saya sering memikirkan kekurangan diri lebih lama daripada keberhasilan yang saya capai.','AC','signal',14),
('MEMAHAMI_DIRI','SU1','Saya memiliki setidaknya satu orang yang benar-benar dapat saya percaya untuk bercerita.','SU','private',15),
('MEMAHAMI_DIRI','SU2','Saya merasa memiliki orang yang dapat membantu ketika sedang mengalami masa sulit.','SU','private',16),
('MEMAHAMI_DIRI','HS1','Saya cukup nyaman meminta bantuan ketika memang membutuhkannya.','HS','private',17),
('MEMAHAMI_DIRI','HS2','Saya merasa lingkungan ETOS dapat menjadi salah satu tempat untuk mencari dukungan.','HS','private',18),
('MEMAHAMI_DIRI','XF1','Ada persoalan keluarga yang belakangan ini cukup memengaruhi pikiran saya.','XF','signal',19),
('MEMAHAMI_DIRI','XR1','Ada persoalan pertemanan atau hubungan dengan orang lain yang sedang mengganggu saya.','XR','signal',20),
('MEMAHAMI_DIRI','XA1','Tekanan akademik belakangan ini terasa cukup berat bagi saya.','XA','signal',21),
('MEMAHAMI_DIRI','XM1','Saya sedang cukup bingung mengenai diri atau masa depan saya.','XM','signal',22),
('MEMAHAMI_DIRI','CK1','Saya merasa ada sesuatu yang ingin saya bicarakan secara pribadi dengan fasilitator.','CK','signal',23),
('MEMAHAMI_DIRI','CK2','Saya merasa akan terbantu jika mendapat pendampingan lebih dekat dalam beberapa waktu ke depan.','CK','signal',24),
('MENENTUKAN_ARAH','FC1','Saya sudah memiliki gambaran mengenai profesi yang ingin saya jalani.','FC','standard',1),
('MENENTUKAN_ARAH','FC2','Saya mengetahui kemampuan apa yang perlu saya bangun untuk mendekati cita-cita saya.','FC','standard',2),
('MENENTUKAN_ARAH','FC3','Saya memiliki target tertentu yang ingin saya capai selama masa kuliah.','FC','standard',3),
('MENENTUKAN_ARAH','FE1','Saya mempunyai beberapa pilihan karier yang sedang saya pertimbangkan.','FE','standard',4),
('MENENTUKAN_ARAH','FE2','Saya masih ingin mencoba banyak pengalaman sebelum menentukan pilihan karier.','FE','standard',5),
('MENENTUKAN_ARAH','FE3','Saya ingin masa kuliah menjadi waktu untuk menemukan arah hidup dengan lebih jelas.','FE','standard',6),
('MENENTUKAN_ARAH','R1','Saya menikmati kegiatan yang menggunakan alat, teknologi, atau keterampilan praktis.','R','standard',7),
('MENENTUKAN_ARAH','R2','Saya tertarik membuat, merakit, memperbaiki, atau mengoperasikan sesuatu.','R','standard',8),
('MENENTUKAN_ARAH','I1','Saya menikmati mencari tahu penyebab suatu masalah.','I','standard',9),
('MENENTUKAN_ARAH','I2','Saya tertarik melakukan penelitian, analisis, atau mempelajari sesuatu secara mendalam.','I','standard',10),
('MENENTUKAN_ARAH','A1','Saya menikmati menciptakan ide, desain, tulisan, konten, atau karya.','A','standard',11),
('MENENTUKAN_ARAH','A2','Saya menyukai aktivitas yang memberi ruang besar untuk kreativitas dan ekspresi.','A','standard',12),
('MENENTUKAN_ARAH','S1','Saya menikmati membantu orang memahami sesuatu.','S','standard',13),
('MENENTUKAN_ARAH','S2','Saya senang ketika dapat mendampingi atau memberi manfaat langsung kepada orang lain.','S','standard',14),
('MENENTUKAN_ARAH','E1','Saya menikmati mengajak orang lain bergerak mencapai suatu tujuan.','E','standard',15),
('MENENTUKAN_ARAH','E2','Saya tertarik membangun usaha, organisasi, program, atau sesuatu yang dapat berkembang.','E','standard',16),
('MENENTUKAN_ARAH','C1','Saya menikmati mengatur data, sistem, jadwal, atau pekerjaan agar lebih rapi.','C','standard',17),
('MENENTUKAN_ARAH','C2','Saya nyaman mengerjakan sesuatu yang membutuhkan ketelitian dan keteraturan.','C','standard',18),
('MENENTUKAN_ARAH','AL1','Saya tertarik memimpin organisasi, tim, atau project.','AL','standard',19),
('MENENTUKAN_ARAH','AE1','Saya tertarik membangun usaha sendiri atau menjadi entrepreneur.','AE','standard',20),
('MENENTUKAN_ARAH','AS1','Saya tertarik menghasilkan dampak sosial melalui pekerjaan atau kegiatan saya.','AS','standard',21),
('MENENTUKAN_ARAH','AG1','Saya ingin memiliki pengalaman belajar atau bekerja di luar daerah atau lingkungan internasional.','AG','standard',22),
('MENENTUKAN_ARAH','CP1','Saya tertarik bekerja di perusahaan atau lingkungan profesional.','CP','standard',23),
('MENENTUKAN_ARAH','CE1','Saya tertarik menjadikan entrepreneurship sebagai salah satu jalur masa depan.','CE','standard',24),
('MENENTUKAN_ARAH','CA1','Saya tertarik menjadi akademisi, peneliti, atau melanjutkan pendidikan tinggi.','CA','standard',25),
('MENENTUKAN_ARAH','CG1','Saya tertarik bekerja di pemerintahan atau pelayanan publik.','CG','standard',26),
('MENENTUKAN_ARAH','CS1','Saya tertarik bekerja dalam NGO, organisasi sosial, atau community development.','CS','standard',27),
('MENENTUKAN_ARAH','CD1','Saya tertarik menjadi pendidik atau terlibat dalam pengembangan manusia.','CD','standard',28),
('MENENTUKAN_ARAH','VN1','Saya ingin pekerjaan saya memberikan manfaat nyata bagi orang lain.','VN','standard',29),
('MENENTUKAN_ARAH','VF1','Saya ingin memiliki kemandirian finansial.','VF','standard',30),
('MENENTUKAN_ARAH','VS1','Saya ingin kehidupan profesional saya tetap selaras dengan nilai agama.','VS','standard',31),
('MENENTUKAN_ARAH','VL1','Saya ingin terus memperoleh pengalaman dan pengetahuan baru sepanjang hidup.','VL','standard',32),
('MENENTUKAN_ARAH','KD1','Ada persoalan di masyarakat atau daerah asal yang suatu saat ingin saya bantu selesaikan.','KD','standard',33),
('MENENTUKAN_ARAH','KD2','Saya ingin menggunakan bidang ilmu saya untuk memberikan manfaat kepada masyarakat.','KD','standard',34)
)
insert into public.assessment_questions(module_id,code,statement,dimension,sensitivity,sort_order)
select m.id, s.code, s.statement, s.dimension, s.sensitivity, s.sort_order
from src s join public.assessment_modules m on m.code=s.module_code
on conflict (code) do update set
  module_id=excluded.module_id,
  statement=excluded.statement,
  dimension=excluded.dimension,
  sensitivity=excluded.sensitivity,
  sort_order=excluded.sort_order;

-- Safe default period. Admin may adjust dates/status after deployment.
insert into public.assessment_periods(name, academic_year, semester, is_active)
values ('Assessment ETOS 2026 Semester 1','2026',1,true)
on conflict (academic_year,semester) do nothing;
